# main menu navigation
menu:
  主页: /
  博客: /posts
  分类: /archives
  # 体系: /knowledge
  # 项目: /project
  # 关于: /about
  友链: /friend
  留言: /message
  说说: /saysay
  开往: https://travellings.now.sh/

site_name: Sorryfu #网站的名称
author: Sorryfu  #文章的默认作者
icon: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #标签页图标


intro:
  title: Me
  sub: An android developer.
  img: https://cdn.jsdelivr.net/gh/fushaolei/img/20200624215641.jpg

#联系方式
contact:
  Email: 1563250958@qq.com
  QQ: 1563250958

#友链
link:
  Github: https://github.com/FuShaoLei
  Hexo: https://hexo.io
  Typora: https://typora.io
  城南破事: https://www.ronce.cc/
  竹青虫の窝: https://1940879828.github.io/
  CtrlCV博客: https://www.hack-er.cn/
  两小无猜: https://www.cnblogs.com/charlottepl/
  策策的小黑屋: https://www.cnblogs.com/occlive/
  Guan FuQing: https://yiki.tech
  阿瑞: https://wenzia.com


# Valine评论系统
valine:
  open: true # true | false 是否打开，默认false
  appid: HBismw2vU6hg56PslAF2APW1-gzGzoHsz  #Leancloud应用的AppID
  appkey: k41e2BJYdNbojyHuMnKT5LBK  #Leancloud应用的AppKey
  verify: false #验证码
  notify: true #评论回复提醒
  avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  #头像类型可见： https://valine.js.org/avatar.html
  placeholder: 留下你来过的痕迹~ #评论框占位符

plugins:
  # 代码高亮
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/vs2015.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles