# main menu navigation
menu:
  Home: /
  Archives: /archives
  Page: /page

site_name: Sorryfu #网站的名称
author: Sorryfu  #文章的默认作者

#联系方式
contact:
  Email: 1563250958@qq.com
  Github: github.com/FuShaoLei

#友链
link:
  Typora: typora.io
  Hexo: hexo.io

# Valine评论系统
valine:
  open: true # true | false 是否打开，默认false
  appid: HBismw2vU6hg56PslAF2APW1-gzGzoHsz  #Leancloud应用的AppID
  appkey: k41e2BJYdNbojyHuMnKT5LBK  #Leancloud应用的AppKey
  verify: false #验证码
  notify: true #评论回复提醒
  avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  #头像类型可见： https://valine.js.org/avatar.html
  placeholder: 留下你来过的痕迹~ #评论框占位符

plugins:
  # 代码高亮
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.0.3/styles/srcery.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles